name: Generate and Publish SDKs with Speakeasy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-codeartifacts:
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get CodeArtifact authorization token
        id: codeartifact-token
        run: |
          TOKEN=$(aws codeartifact get-authorization-token \
            --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} \
            --query authorizationToken \
            --output text)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

          REPO_URL=$(aws codeartifact get-repository-endpoint \
            --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} \
            --repository ${{ secrets.CODEARTIFACT_REPO }} \
            --format pypi \
            --query repositoryEndpoint \
            --output text)
          echo "repo_url=$REPO_URL" >> $GITHUB_OUTPUT

      - name: Build Python package
        run: |
          hatch build

      - name: Publish to CodeArtifact
        env:
          CODEARTIFACT_TOKEN: ${{ steps.codeartifact-token.outputs.token }}
          REPO_URL: ${{ steps.codeartifact-token.outputs.repo_url }}
        run: |
          # Configure uv to use CodeArtifact
          uv publish \
            --publish-url "${REPO_URL}" \
            --password "${CODEARTIFACT_TOKEN}" \
            --username aws
