name: Build SDK and publish to AWS CodeArtifact

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-codeartifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Dependencies
        run: pip install .

      - name: Build Python package
        run: |
          hatch build

      - name: Login to CodeArtifact
        run: |
          aws --version
          aws codeartifact login \
          --tool twine \
          --repository ${{ secrets.AWS_CODEARTIFACT_REPO }} \
          --domain ${{ secrets.AWS_CODEARTIFACT_DOMAIN }} \
          --domain-owner ${{ secrets.AWS_CODEARTIFACT_DOMAIN_OWNER }} \
          --region ${{ secrets.AWS_REGION }}

      - name: Publish to CodeArtifact
        run: |
          twine upload --repository codeartifact dist/*
